#Naming the file.
name: Scrape
#When to run.
on:
  schedule:
    #Cron = scheduling tool that tells your computer when to run tasks. First, the minute. Second, the hour. Third is the day of the week, fourth is the month, and last is the year. You can google an online tool that'll take an English time expression and translate into cron. This one runs stuff at 8 a.m. UTC every day.
    - cron: "0 8 * * *"
  workflow_dispatch:
#What tasks to execute.
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        cache: 'pipenv'
    - run: pipenv install jupyter requests bs4 --python `which python`
      #Runs scraper.
    - name: Run scraper
      run: pipenv run jupyter execute scrape.ipynb
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest data"
